import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { AuthProvider } from "./context/authContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="es">
      <body className="min-h-screen grid grid-rows-[auto_1fr_auto] font-serif">
        <AuthProvider>
          <Navbar />
          <div className="flex flex-col justify-center items-center p-8">
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}